const CLIENT_BFF = '/api/client'
const EMPLOYEE_BFF = '/api/employee'

export const endpoints = {
  auth: {
    register: '/auth/api/v1/auth/register',
    token: '/auth/oauth2/token',
    authorize: '/auth/oauth2/authorize',
  },
  client: {
    accounts: `${CLIENT_BFF}/accounts`,
    account: (id: number) => `${CLIENT_BFF}/accounts/${id}`,
    deposit: (id: number) => `${CLIENT_BFF}/accounts/${id}/deposit`,
    withdraw: (id: number) => `${CLIENT_BFF}/accounts/${id}/withdraw`,
    operations: (id: number) => `${CLIENT_BFF}/accounts/${id}/operations`,
    transfers: `${CLIENT_BFF}/transfers`,
    credits: `${CLIENT_BFF}/credits`,
    credit: (id: number) => `${CLIENT_BFF}/credits/${id}`,
    creditPayments: (id: number) => `${CLIENT_BFF}/credits/${id}/payments`,
    creditRepay: (id: number) => `${CLIENT_BFF}/credits/${id}/repay`,
    tariffs: `${CLIENT_BFF}/proxy/credit/tariffs`,
    creditRating: (userId: number) => `${CLIENT_BFF}/proxy/credit/users/${userId}/credit-rating`,
    users: `${CLIENT_BFF}/proxy/user/users`,
    user: (id: number) => `${CLIENT_BFF}/proxy/user/users/${id}`,
    userByEmail: `${CLIENT_BFF}/proxy/user/users/by-email`,
    settings: `${CLIENT_BFF}/settings`,
  },
  employee: {
    accounts: `${EMPLOYEE_BFF}/proxy/core/accounts`,
    account: (id: number) => `${EMPLOYEE_BFF}/proxy/core/accounts/${id}`,
    operations: (id: number) => `${EMPLOYEE_BFF}/proxy/core/accounts/${id}/operations`,
    masterAccount: `${EMPLOYEE_BFF}/proxy/core/master-account`,
    credits: `${EMPLOYEE_BFF}/proxy/credit/credits`,
    credit: (id: number) => `${EMPLOYEE_BFF}/proxy/credit/credits/${id}`,
    creditPayments: (id: number) => `${EMPLOYEE_BFF}/proxy/credit/credits/${id}/payments`,
    tariffs: `${EMPLOYEE_BFF}/proxy/credit/tariffs`,
    creditRating: (userId: number) => `${EMPLOYEE_BFF}/proxy/credit/users/${userId}/credit-rating`,
    users: `${EMPLOYEE_BFF}/proxy/user/users`,
    user: (id: number) => `${EMPLOYEE_BFF}/proxy/user/users/${id}`,
    userBlock: (id: number) => `${EMPLOYEE_BFF}/proxy/user/users/${id}/block`,
    userUnblock: (id: number) => `${EMPLOYEE_BFF}/proxy/user/users/${id}/unblock`,
    userRoles: (id: number) => `${EMPLOYEE_BFF}/users/${id}/roles`,
    availableRoles: `${EMPLOYEE_BFF}/proxy/user/users/roles`,
    settings: `${EMPLOYEE_BFF}/settings`,
  },
} as const
