server:
  port: 8083

spring:
  application:
    name: credit-service
  datasource:
    url: jdbc:postgresql://localhost:5435/bank_credit
    username: bank
    password: bank_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

services:
  core-service:
    url: http://localhost:8080

credit:
  payment-schedule: "0 0 0 * * *"
