spring:
  datasource:
    url: jdbc:postgresql://postgres-employee-bff:5432/bank_employee_bff
  data:
    redis:
      host: redis
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/oauth2/jwks
  kafka:
    bootstrap-servers: kafka:9092

services:
  core-service:
    url: http://core-service:8080
  user-service:
    url: http://user-service:8082
  credit-service:
    url: http://credit-service:8083
